# Generated by Django 5.2.9 on 2026-04-08 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("match_score", models.FloatField(default=100.0)),
                (
                    "match_reason",
                    models.TextField(blank=True, help_text="Why did this match?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buybox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_matches",
                        to="buyers.buybox",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_matches",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Property Matches",
                "unique_together": {("property", "buybox")},
            },
        ),
    ]
