# Generated by Django 5.2.9 on 2026-04-08 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("blinq_or_website", models.URLField(blank=True, max_length=500)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Where are you located?", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BuyBox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        help_text="Primary Asset Class (Derived from Sheet Tab)",
                        max_length=255,
                    ),
                ),
                (
                    "target_states",
                    models.TextField(
                        help_text="Comma-separated list of states they are buying in"
                    ),
                ),
                (
                    "area_preference",
                    models.CharField(
                        help_text="Metro, suburban, or rural areas?", max_length=255
                    ),
                ),
                (
                    "virtual_acquisitions",
                    models.CharField(
                        help_text="Are you open to virtual acquisitions? (Yes/No)",
                        max_length=50,
                    ),
                ),
                (
                    "property_types",
                    models.TextField(
                        help_text="What type of properties do you buy? (Stored as a list)"
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        help_text="What is your ideal purchase price range?",
                        max_length=255,
                    ),
                ),
                (
                    "is_cash_buyer",
                    models.CharField(help_text="Are you a cash buyer?", max_length=50),
                ),
                (
                    "deal_structures",
                    models.TextField(
                        help_text="All Cash, Subject-To, Seller Finance, etc."
                    ),
                ),
                (
                    "equity_arv_requirement",
                    models.TextField(
                        help_text="Do you require a specific equity spread or ARV percentage?"
                    ),
                ),
                (
                    "property_condition",
                    models.TextField(
                        help_text="What level of property condition are you open to purchasing?"
                    ),
                ),
                (
                    "cheat_codes",
                    models.CharField(
                        blank=True, help_text="Cheat Codes", max_length=255
                    ),
                ),
                (
                    "strategy_notes",
                    models.TextField(
                        blank=True,
                        help_text="Anything else we should know about your buy box or investment strategy?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_boxes",
                        to="buyers.buyer",
                    ),
                ),
            ],
        ),
    ]
