# Generated by Django 5.2.9 on 2026-04-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyers", "0002_add_slugs"),
        ("parcels", "0005_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="buybox",
            name="comp_search_tiers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Comp search tiers: [{radius_ft, lookback_months, label}]",
            ),
        ),
        migrations.AddField(
            model_name="buybox",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="County this buybox targets (links to GIS config)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buyboxes",
                to="parcels.county",
            ),
        ),
        migrations.AddField(
            model_name="buybox",
            name="duplex_scoring_enabled",
            field=models.BooleanField(
                default=True, help_text="Whether to run duplex friendliness scoring"
            ),
        ),
        migrations.AddField(
            model_name="buybox",
            name="max_acres",
            field=models.FloatField(
                blank=True,
                help_text="Maximum acreage filter (null = no max)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="buybox",
            name="max_price",
            field=models.IntegerField(
                blank=True, help_text="Maximum appraised value filter", null=True
            ),
        ),
        migrations.AddField(
            model_name="buybox",
            name="min_acres",
            field=models.FloatField(
                blank=True, help_text="Minimum acreage filter", null=True
            ),
        ),
        migrations.AddField(
            model_name="buybox",
            name="min_compactness",
            field=models.FloatField(
                default=0.25, help_text="Minimum lot compactness score (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="buybox",
            name="target_geography",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Geography filters: {target_districts: [...], exclude_districts: [...], mixed_districts: {...}}",
            ),
        ),
        migrations.AddField(
            model_name="buybox",
            name="target_zoning",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Zoning codes to match, e.g. ["R-2"]',
            ),
        ),
    ]
