# Generated by Django 5.2.9 on 2026-04-08 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=20)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(max_length=255)),
                ("main_phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("employee_range", models.CharField(blank=True, max_length=100)),
                ("annual_sales", models.CharField(blank=True, max_length=100)),
                ("sic_code", models.CharField(blank=True, max_length=50)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Properties",
                "unique_together": {("address", "zip_code")},
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=150)),
                ("direct_phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
