# Generated by Django 5.0.6 on 2025-12-20 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LandingPageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_hook_frustration",
                    models.TextField(help_text="Frustration-based hook template"),
                ),
                (
                    "hero_hook_results",
                    models.TextField(help_text="Results-based hook template"),
                ),
                ("hero_subheading", models.TextField()),
                (
                    "cta_text",
                    models.CharField(default="Start the quiz", max_length=100),
                ),
                ("cta_microcopy", models.CharField(blank=True, max_length=255)),
                ("value_prop_area_1", models.CharField(max_length=255)),
                ("value_prop_area_2", models.CharField(max_length=255)),
                ("value_prop_area_3", models.CharField(max_length=255)),
                ("bio_name", models.CharField(blank=True, max_length=255)),
                ("bio_role", models.CharField(blank=True, max_length=255)),
                ("bio_text", models.TextField(blank=True)),
                ("research_text", models.TextField(blank=True)),
                (
                    "stats_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of statistics/research statements",
                    ),
                ),
                (
                    "funnel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_page",
                        to="funnels.funnel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("score", models.FloatField(blank=True, null=True)),
                ("tier_label", models.CharField(blank=True, max_length=50)),
                ("next_step_type", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "funnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="funnels.funnel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BEST_PRACTICE", "Best Practice (0-100 score)"),
                            ("BIG_FIVE", "Big Five (Qualification)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Weight for scoring (only for BEST_PRACTICE)",
                    ),
                ),
                (
                    "funnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="funnels.funnel",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "value",
                    models.FloatField(
                        default=0, help_text="Points awarded for this choice"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="funnels.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_value", models.TextField(blank=True)),
                (
                    "choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="funnels.choice",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="funnels.lead",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funnels.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_score", models.FloatField()),
                ("max_score", models.FloatField()),
                ("label", models.CharField(max_length=50)),
                ("headline", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "funnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="funnels.funnel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "funnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="funnels.funnel",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funnels.resulttier",
                    ),
                ),
            ],
        ),
    ]
