# Generated by Django 5.2.9 on 2026-04-15 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parcel_id",
                    models.CharField(
                        help_text="Tax map number e.g. '155P H 001'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("county", models.CharField(default="Hamilton", max_length=100)),
                ("state", models.CharField(default="TN", max_length=10)),
                ("owner_name", models.CharField(blank=True, max_length=255)),
                ("owner_name_2", models.CharField(blank=True, max_length=255)),
                ("owner_mailing", models.CharField(blank=True, max_length=500)),
                (
                    "calc_acres",
                    models.FloatField(
                        blank=True, help_text="GIS-reported acreage", null=True
                    ),
                ),
                (
                    "computed_acres",
                    models.FloatField(
                        blank=True,
                        help_text="Computed from polygon geometry",
                        null=True,
                    ),
                ),
                (
                    "compactness",
                    models.FloatField(
                        blank=True, help_text="Shape compactness score 0-1", null=True
                    ),
                ),
                ("land_value", models.IntegerField(default=0)),
                ("building_value", models.IntegerField(default=0)),
                ("appraised_value", models.IntegerField(default=0)),
                ("assessed_value", models.IntegerField(default=0)),
                ("zoning", models.CharField(blank=True, default="R-2", max_length=20)),
                ("land_use_code", models.CharField(blank=True, max_length=20)),
                ("district", models.CharField(blank=True, max_length=20)),
                ("water_provider", models.CharField(blank=True, max_length=255)),
                ("sewer_provider", models.CharField(blank=True, max_length=255)),
                ("utilities_score", models.CharField(blank=True, max_length=50)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "geometry_rings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Polygon rings as [[lat,lon],...] for Leaflet",
                    ),
                ),
                ("last_sale_date", models.CharField(blank=True, max_length=50)),
                ("last_sale_price", models.IntegerField(default=0)),
                ("assessor_link", models.URLField(blank=True, max_length=500)),
                ("land_comp_count", models.IntegerField(default=0)),
                ("land_comp_radius", models.CharField(blank=True, max_length=50)),
                ("land_comp_min", models.IntegerField(blank=True, null=True)),
                ("land_comp_max", models.IntegerField(blank=True, null=True)),
                ("land_comp_median", models.FloatField(blank=True, null=True)),
                ("land_comp_avg_ppa", models.FloatField(blank=True, null=True)),
                ("land_est_value", models.FloatField(blank=True, null=True)),
                ("land_comp_details", models.TextField(blank=True)),
                ("arv_comp_count", models.IntegerField(default=0)),
                ("arv_comp_radius", models.CharField(blank=True, max_length=50)),
                ("arv_comp_min", models.IntegerField(blank=True, null=True)),
                ("arv_comp_max", models.IntegerField(blank=True, null=True)),
                ("arv_comp_median", models.FloatField(blank=True, null=True)),
                ("arv_comp_details", models.TextField(blank=True)),
                ("nearby_sfr", models.IntegerField(default=0)),
                ("nearby_duplex", models.IntegerField(default=0)),
                ("nearby_triplex", models.IntegerField(default=0)),
                ("nearby_quad", models.IntegerField(default=0)),
                ("nearby_total", models.IntegerField(default=0)),
                ("duplex_ratio", models.FloatField(blank=True, null=True)),
                (
                    "duplex_friendliness",
                    models.CharField(
                        blank=True, help_text="A/B/C/D grade", max_length=1
                    ),
                ),
                ("deal_tier", models.CharField(blank=True, max_length=10)),
                ("geo_priority", models.CharField(blank=True, max_length=100)),
                ("is_target", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buybox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_parcels",
                        to="buyers.buybox",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parcels",
                "ordering": ["geo_priority", "duplex_friendliness", "parcel_id"],
            },
        ),
        migrations.CreateModel(
            name="ParcelRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("maybe", "Maybe"),
                            ("no", "No"),
                            ("skip", "Skip"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="parcels.parcel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompParcel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "comp_type",
                    models.CharField(
                        choices=[("land", "Land Comp"), ("arv", "ARV Comp")],
                        max_length=10,
                    ),
                ),
                ("distance_ft", models.FloatField(blank=True, null=True)),
                ("sale_price", models.IntegerField(blank=True, null=True)),
                ("sale_date", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comp_for",
                        to="parcels.parcel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comps",
                        to="parcels.parcel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comp Parcels",
                "unique_together": {("target", "comp", "comp_type")},
            },
        ),
    ]
