# Generated by Django 5.2.9 on 2026-04-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcelrating",
            name="sort_order",
            field=models.IntegerField(
                default=0,
                help_text="Manual sort order within rating category (lower = higher priority)",
            ),
        ),
    ]
