# Generated by Django 5.2.9 on 2026-04-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcels", "0002_parcelrating_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="adjacent_details",
            field=models.TextField(
                blank=True, help_text="Details of adjacent same-owner parcels"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="owner_adjacent",
            field=models.BooleanField(
                default=False, help_text="Owner has an adjacent parcel"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="owner_lives_adjacent",
            field=models.BooleanField(
                default=False,
                help_text="Owner has adjacent parcel with a building (lives next door)",
            ),
        ),
    ]
