# Generated by Django 5.2.9 on 2026-04-15 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcels", "0003_parcel_adjacent_details_parcel_owner_adjacent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Owner name as it appears on county records",
                        max_length=255,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("mailing_address", models.CharField(blank=True, max_length=500)),
                ("phone_1", models.CharField(blank=True, max_length=50)),
                (
                    "phone_1_type",
                    models.CharField(
                        blank=True, help_text="Landline/Wireless/VoIP", max_length=20
                    ),
                ),
                ("phone_2", models.CharField(blank=True, max_length=50)),
                ("phone_2_type", models.CharField(blank=True, max_length=20)),
                ("phone_3", models.CharField(blank=True, max_length=50)),
                ("phone_3_type", models.CharField(blank=True, max_length=20)),
                ("email_1", models.EmailField(blank=True, max_length=254)),
                ("email_2", models.EmailField(blank=True, max_length=254)),
                ("email_3", models.EmailField(blank=True, max_length=254)),
                ("age", models.CharField(blank=True, max_length=10)),
                ("skip_traced", models.BooleanField(default=False)),
                ("skip_trace_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Owners",
            },
        ),
        migrations.AddField(
            model_name="parcel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parcels",
                to="parcels.owner",
            ),
        ),
    ]
