# Generated by Django 5.2.9 on 2026-04-16 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcels", "0004_owner_parcel_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=10)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "fips",
                    models.CharField(
                        blank=True, help_text="FIPS county code", max_length=10
                    ),
                ),
                (
                    "parcel_layer_url",
                    models.URLField(
                        help_text="ArcGIS REST parcel layer URL", max_length=500
                    ),
                ),
                (
                    "parcel_layer_wkid",
                    models.IntegerField(
                        default=6576,
                        help_text="Spatial reference WKID for parcel layer",
                    ),
                ),
                (
                    "zoning_layer_url",
                    models.URLField(
                        blank=True,
                        help_text="ArcGIS REST zoning layer URL",
                        max_length=500,
                    ),
                ),
                (
                    "zoning_layer_wkid",
                    models.IntegerField(
                        default=2274,
                        help_text="Spatial reference WKID for zoning layer",
                    ),
                ),
                (
                    "zoning_zone_field",
                    models.CharField(
                        default="ZONE",
                        help_text="Field name for zone designation",
                        max_length=50,
                    ),
                ),
                ("water_layer_url", models.URLField(blank=True, max_length=500)),
                (
                    "water_layer_provider_field",
                    models.CharField(blank=True, default="DISTRICT", max_length=50),
                ),
                ("sewer_layer_url", models.URLField(blank=True, max_length=500)),
                (
                    "sewer_layer_provider_field",
                    models.CharField(
                        blank=True, default="ServiceProvider", max_length=50
                    ),
                ),
                (
                    "field_map",
                    models.JSONField(
                        default=dict,
                        help_text="Maps canonical names to GIS field names: {parcel_id: TAX_MAP_NO, address: ADDRESS, ...}",
                    ),
                ),
                (
                    "entity_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="County-specific entity keywords e.g. ['CHATT CITY', 'HAMILTON COUNTY']",
                    ),
                ),
                (
                    "out_sr",
                    models.IntegerField(
                        default=4326,
                        help_text="Output spatial reference for lat/lon (usually WGS84 = 4326)",
                    ),
                ),
                ("max_records_per_query", models.IntegerField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Counties",
                "unique_together": {("name", "state")},
            },
        ),
    ]
