# Generated by Django 5.2.9 on 2026-04-17 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parcels", "0005_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="county",
            name="market_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="State/county-specific rules. Keys:\n  prop_13: bool — CA Prop 13 frozen assessments\n  assessment_reflects_market: bool — whether assessed value tracks market value\n  reassessment_frequency: str — 'annual', 'biennial', 'on_sale', etc.\n  homestead_exempt: bool — FL/TX homestead exemption affects analysis\n  transfer_tax_rate: float — documentary stamp / transfer tax %\n  disclosure_state: bool — seller must disclose defects\n  comp_strategy: str — 'land_arv' (vacant land), 'acquisition_arv' (fix-flip), 'single'\n  flip_indicators: list — which fields indicate distress in this market\n  notes: str — free-form notes about this market",
            ),
        ),
        migrations.CreateModel(
            name="MarketSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcel_count",
                    models.IntegerField(default=0, help_text="Total parcels queried"),
                ),
                ("median_total_value", models.IntegerField(blank=True, null=True)),
                (
                    "median_ppsf",
                    models.FloatField(
                        blank=True, help_text="Median price per sqft", null=True
                    ),
                ),
                ("median_land_value", models.IntegerField(blank=True, null=True)),
                ("median_impr_ratio", models.FloatField(blank=True, null=True)),
                (
                    "ppa_floor",
                    models.FloatField(
                        blank=True,
                        help_text="25th percentile $/acre for land comps",
                        null=True,
                    ),
                ),
                (
                    "ppa_cap",
                    models.FloatField(
                        blank=True,
                        help_text="3x median $/acre for land comps",
                        null=True,
                    ),
                ),
                ("community_stats", models.JSONField(blank=True, default=dict)),
                (
                    "flip_rate",
                    models.FloatField(
                        blank=True,
                        help_text="% of recent sales that are likely flips",
                        null=True,
                    ),
                ),
                ("flip_non_owner_occ_rate", models.FloatField(blank=True, null=True)),
                ("flip_median_ppsf", models.FloatField(blank=True, null=True)),
                ("yearly_trends", models.JSONField(blank=True, default=dict)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="parcels.county",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
                "get_latest_by": "computed_at",
            },
        ),
        migrations.CreateModel(
            name="GISParcelCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parcel_id",
                    models.CharField(help_text="APN or tax map number", max_length=50),
                ),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "address",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "community",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "total_value",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("land_value", models.IntegerField(blank=True, null=True)),
                ("impr_value", models.IntegerField(blank=True, null=True)),
                ("sqft", models.IntegerField(blank=True, null=True)),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("acreage", models.FloatField(blank=True, null=True)),
                (
                    "owner_occupied",
                    models.BooleanField(blank=True, db_index=True, null=True),
                ),
                (
                    "sale_year",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "land_use_code",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("geometry_rings", models.JSONField(blank=True, default=list)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcel_cache",
                        to="parcels.county",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["county", "land_use_code", "total_value"],
                        name="parcels_gis_county__cd5586_idx",
                    ),
                    models.Index(
                        fields=["county", "community", "total_value"],
                        name="parcels_gis_county__631172_idx",
                    ),
                    models.Index(
                        fields=["county", "sale_year"],
                        name="parcels_gis_county__7bc6bf_idx",
                    ),
                ],
                "unique_together": {("county", "parcel_id")},
            },
        ),
    ]
